#include "LIPSBodyPoseTypes.h"
using namespace lips;

const enum LIPSBODYPOSE_KEYPOINT_ENUM POSE_PARTS_RENDER[] = {
    LIPSBODYPOSE_R_EYE, LIPSBODYPOSE_L_EYE, LIPSBODYPOSE_R_EAR,
    LIPSBODYPOSE_L_EAR, LIPSBODYPOSE_NOSE, LIPSBODYPOSE_NECK,
    LIPSBODYPOSE_R_SHOULDER, LIPSBODYPOSE_R_ELBOW, LIPSBODYPOSE_R_WRIST,
    LIPSBODYPOSE_L_SHOULDER, LIPSBODYPOSE_L_ELBOW, LIPSBODYPOSE_L_WRIST,
    LIPSBODYPOSE_R_HIP, LIPSBODYPOSE_R_KNEE, LIPSBODYPOSE_R_ANKLE,
    LIPSBODYPOSE_L_HIP, LIPSBODYPOSE_L_KNEE, LIPSBODYPOSE_L_ANKLE};

const enum LIPSBODYPOSE_KEYPOINT_ENUM POSE_PAIRS_RENDER[][2] = {
    // Face
    {LIPSBODYPOSE_R_EYE, LIPSBODYPOSE_R_EAR},
    {LIPSBODYPOSE_L_EYE, LIPSBODYPOSE_L_EAR},
    {LIPSBODYPOSE_R_EYE, LIPSBODYPOSE_NOSE},
    {LIPSBODYPOSE_L_EYE, LIPSBODYPOSE_NOSE},
    // Body
    {LIPSBODYPOSE_NOSE, LIPSBODYPOSE_NECK},
    {LIPSBODYPOSE_NECK, LIPSBODYPOSE_R_SHOULDER},
    {LIPSBODYPOSE_NECK, LIPSBODYPOSE_L_SHOULDER},
    {LIPSBODYPOSE_R_SHOULDER, LIPSBODYPOSE_R_HIP},
    {LIPSBODYPOSE_L_SHOULDER, LIPSBODYPOSE_L_HIP},
    {LIPSBODYPOSE_L_HIP, LIPSBODYPOSE_R_HIP},
    // Right arm
    {LIPSBODYPOSE_R_SHOULDER, LIPSBODYPOSE_R_ELBOW},
    {LIPSBODYPOSE_R_ELBOW, LIPSBODYPOSE_R_WRIST},
    // Left arm
    {LIPSBODYPOSE_L_SHOULDER, LIPSBODYPOSE_L_ELBOW},
    {LIPSBODYPOSE_L_ELBOW, LIPSBODYPOSE_L_WRIST},
    // Right leg
    {LIPSBODYPOSE_R_HIP, LIPSBODYPOSE_R_KNEE},
    {LIPSBODYPOSE_R_KNEE, LIPSBODYPOSE_R_ANKLE},
    // Left leg
    {LIPSBODYPOSE_L_HIP, LIPSBODYPOSE_L_KNEE},
    {LIPSBODYPOSE_L_KNEE, LIPSBODYPOSE_L_ANKLE}};

const float LINE_COLORS[] = {
    // Body
    0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8,
    // Right arm
    0.0, 0.5, 0.0, 0.0, 0.5, 0.0,
    // Left arm
    1.0, 0.0, 0.5, 1.0, 0.0, 0.5,
    // Right leg
    0.0, 1.0, 0.5, 0.0, 1.0, 0.5,
    // Left leg
    0.5, 0.0, 1.0, 0.5, 0.0, 1.0};